apiVersion: v1
kind: Service
metadata:
  name: zmqkafkatest-server
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
  selector:
    app: zmqkafkatest-server
---
apiVersion: v1
kind: Pod
metadata:
  name: zmqkafkatest-server
  labels:
    app: zmqkafkatest-server
spec:
  containers:
  - name: zmqkafkatest-server
    image: repo-billerica.perform.empirix.com:6000/empirix-eva-ecc/zmqkafkatest:2.9.53-feature-IN-36960-initial-delay
    command: ["/home/hammer/hmcliutils/bin/hmzmqkafkatest"]
    args: ["--zmq=tcp", "--server", "--packets=10000", "--csv", "--initial-delay=10"]
    ports:
    - containerPort: 5555
